spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      show_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    driver-class-name: ${DB_DRIVER}
    username: ${DB_USER}
    password: ${DB_PASS}
    url: ${DB_URL}
    hikari:
      maximum-pool-size: 2
      
discord:
  token: ${DISCORD_TOKEN}
  ownerid: ${DISCORD_OWNERID}
  
reddit:
  clientid: ${REDDIT_CLIENTID}
  clientsecret: ${REDDIT_SECRET}
  
humblebundle:
  url: ${HUMBLE_BUNDLE_URL}
  root: ${HUMBLE_BUNDLE_SITE}

logging:
  level:
    #org.hibernate.SQL: DEBUG
    bar.barinade: TRACE